---

tasks:
  - name: Include GoLang
    tags: 
      - languages
      - languages.golang
    include:
      name: packages/golang
      state: ${{ languages | enabled("golang") | ternary('present', 'absent') }}
    when:
      - languages | enabled("golang")

  - name: Install golangci-lint
    tags: 
      - languages
      - languages.golang
    when:
      - languages | enabled("golang")
    xget:
      package: "golangci/golangci-lint"
      state: ${{ languages | enabled("golang") | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join('golangci-lint') | extension("exe") }}

  - name: Install GoReleaser
    tags: 
      - languages
      - languages.golang
    xget:
      package: "goreleaser/goreleaser"
      state: ${{ languages | enabled("golang") | ternary('present', 'absent') }}
      args:
        - --to=${{ facts.local_bin_path | join('goreleaser') | extension("exe") }}
        - --ignore=.sbom.json
    when:
      - languages | enabled("golang")