---

tasks:
  - name: Include Editors
    include:
      name: roles/development/editors
    when:
      - development | enabled("editors")

  - name: Include Git
    include:
      name: roles/development/git
    when:
      - development | enabled("git")