---

vars: 

  wsl:
    ui: false

  languages:
    golang: false
    nodejs: false
    python: false
    rust: false

  development:
    editors:
      vscode: false
      micro: true
      nano: true

  shells:
    zoxide: true
    pwsh:
      omp:
        profile: "~/.config/powershell/default.omp.json"
      profile: "~/.config/powershell/profile.ps1"

tasks:

  - name: Include base host configuration
    include:
      name: hosts/base