---

vars: 

  wsl:
    ui: false

  languages:
    golang: true
    nodejs: true
    python: true

  development:
    editors:
      vscode: true
      micro: true

tasks:

  - name: Include base host configuration
    include:
      name: hosts/base