---

vars: 
  user:
    paths:
      development:
        work: 
          windows: D:/Development/work/
          wsl: /mnt/d/Development/work/
          default: ~/Development/work/
        oss:
          windows: D:/Development/projects/
          wsl: /mnt/d/Development/projects/
          default: ~/Development/oss/

  wsl:
    ui: false

  languages:
    golang: false
    nodejs: false
    python: false
    rust: true

  development:
    editors:
      vscode: false
      micro: false
      nano: true

  shells:
    zoxide: true
    zsh: true
    pwsh:
      omp:
        profile: "~/.config/powershell/default.omp.json"
      profile: "~/.config/powershell/profile.ps1"

tasks:

  - name: Include base host configuration
    include:
      name: hosts/base