---

vars: 

  wsl:
    ui: false

  languages:
    golang: false
    nodejs: false
    python: false
    rust: true

  development:
    editors:
      vscode: false
      micro: false
      
tasks:

  - name: Include base host configuration
    include:
      name: hosts/base