---

tasks:
  - name: Install doggo CLI
    tags: 
      - packages.doggo
      - packages.dog
    xget:
      package: mr-karan/doggo
      state: ${{ package.state }}
      args:
        - --to="${{ facts.local_bin_path }}"
        - --upgrade-only

  - name: Create symlink for doggo
    tags:
      - packages.doggo
      - packages.dog
    symlinks:
      src: ${{ facts.local_bin_path | join("doggo") | extension("exe") }}
      dest: ${{ facts.local_bin_path | join("dog") | extension("exe") }}
      state: ${{ package.state }}
