---

vars: 

  shells:
    zoxide: true
    pwsh:
      omp:
        profile: "~/.config/powershell/default.omp.json"
      profile: "~/.config/powershell/profile.ps1"

tasks:

  - name: Include WSL Role
    include:
      name: roles/wsl

  - name: Include Debian-Based Role
    include:
      name: tasks/debian-based

  - name: Include Languages Role
    include:
      name: roles/languages
    when:
      - languages | enabled()

  - name: Include Development Role
    include:
      name: roles/development
    when:
      - development | enabled()

  - name: Include Shells Role
    include:
      name: roles/shells
    when:
      - shells | enabled()

  - name: Include Powershell Facts
    include:
      name: tasks/shell/pwsh/facts
