---

# OS tasks loaded automatically based on the detected OS family

tasks:

  - name: Install Rust (${{ facts.os_family }})
    tags:
      - languages.rust
      - languages
    when:
      - facts.os_family not in ["debian", "alpine", "archlinux", "ubuntu", "darwin", "windows"]
    fail:
      message: "Install Rust: Unsupported OS family: ${{ facts.os_family }}"

  - name: Install Rust
    tags:
      - languages.rust
      - languages
    include:
      name: packages/rust