---

tasks:
  - name: Install Windows Subsystem for Linux (WSL)
    winget:
      package: Microsoft.WSL
      state: present
    when:
      - facts.os_family == 'windows'

  - name: Is WSL Installed Fact
    fact:
      name: wsl_installed
      shell:
        command: Get-Command wsl | Out-Null
      value: ${{ rc == 0 }}
    when:
      - facts.os_family == 'windows'