---

tasks:
  - name: Install Visual Studio Code
    apt:
      package: code
      state: ${{ package.state }}
    when:
      - facts.os_family == "debian" or facts.os_family == "ubuntu"

  - name: Install Visual Studio Code
    pacman:
      package: code
      state: ${{ package.state }}
    when:
      - facts.os_family == "archlinux"

  - name: Install Visual Studio Code
    winget:
      package: Microsoft.VisualStudioCode
      state: ${{ package.state }}
    when:
      - facts.os_family == "windows"

  - name: Install Visual Studio Code
    homebrew:
      package: visual-studio-code
      state: ${{ package.state }}
    when:
      - facts.os_family == "darwin"