---

tasks:
  - name: Install Golang
    tags:
      - golang
    actions:
      - name: Install Golang
        pacman:
          name: go
          state: ${{ package.state }}
        become: true
        when:
          - facts.os_family == "archlinux"

      - name: GOPATH
        fact:
          name: GOPATH
          value: ${{ env("GOPATH") }}

      - name: GOBIN
        fact:
          name: GOBIN
          value: ${{ env(facts.GOPATH | join("bin" ))}}
        when:
          - facts.GOPATH is defined
          - facts.GOPATH != ""

      - name: GOBIN in PATH
        fact:
          name: gopath_in_path
          value: ${{ env("GOBIN") }} in ${{ env("PATH") }}

      - name: Register GoPath
        when:
          - facts.shell_zsh
        blockinfile:
          create: false
          dest: ~/.zshrc
          block: |
            if [ -z "$GOPATH" ]; then
              export GOPATH=$HOME/go
              if [ -z "$PATH" ] || [[ ":$PATH:" != *":$GOPATH/bin:"* ]]; then
                export PATH=$PATH:$GOPATH/bin
              fi
            fi
