---

tasks:
  - name: Golang Package
    tags:
      - golang
    actions:
      - name: GOPATH
        fact:
          name: GOPATH
          value: ${{ env("GOPATH") }}

      - name: GOBIN
        fact:
          name: GOBIN
          value: ${{ facts.GOPATH | join("bin") }}
        when:
          - facts.GOPATH is defined
          - facts.GOPATH != ""

      - name: OS PATH Separator
        fact:
          name: os_path_separator
          value: ${{ (facts.platform == "windows") | ternary(";", ":") }}

      - name: GOBIN in PATH
        fact:
          name: gopath_in_path
          value: ${{ (facts.os_path_separator | concat("", env("PATH")) | concat("", facts.os_path_separator)) | contains(facts.os_path_separator | concat("", facts.GOBIN | default("???NOMATCH???")) | concat("", facts.os_path_separator)) }}

      - name: Register GoPath (zsh)
        when:
          - facts.shell_zsh
          - not facts.gopath_in_path
        blockinfile:
          create: false
          dest: ~/.zshrc
          block: |
            if [ -z "$GOPATH" ]; then
              export GOPATH=$HOME/go
              if [ -z "$PATH" ] || [[ ":$PATH:" != *":$GOPATH/bin:"* ]]; then
                export PATH=$PATH:$GOPATH/bin
              fi
            fi

      - name: Register GoPath (bash)
        when:
          - facts.shell_bash
          - not facts.gopath_in_path
        blockinfile:
          create: false
          dest: ~/.bashrc
          block: |
            if [ -z "$GOPATH" ]; then
              export GOPATH=$HOME/go
              if [ -z "$PATH" ] || [[ ":$PATH:" != *":$GOPATH/bin:"* ]]; then
                export PATH=$PATH:$GOPATH/bin
              fi
            fi

      - name: Register GoPath (fish)
        when:
          - facts.shell_fish
          - not facts.gopath_in_path
        blockinfile:
          create: false
          dest: ~/.config/fish/config.fish
          block: |
            if not set -q GOPATH
              set -x GOPATH $HOME/go
              if not contains $GOPATH/bin $PATH
                set -x PATH $PATH $GOPATH/bin
              end
            end

      - name: Register GoPath (powershell)
        when:
          - facts.shell_powershell
          - not facts.gopath_in_path
        blockinfile:
          create: false
          dest: ~/.config/powershell/profile.ps1
          block: |
            if (-not $env:GOPATH) {
              $env:GOPATH = "$HOME/go"
              if (-not $env:PATH.Contains("$env:GOPATH/bin")) {
                $env:PATH = "$env:PATH;$env:GOPATH/bin"
              }
            }

      - name: Register GoPath (nushell)
        when:
          - facts.shell_nu
          - not facts.gopath_in_path
        blockinfile:
          create: false
          dest: ~/.config/nushell/config.nu
          block: |
            if not $env:GOPATH {
              set -x GOPATH $HOME/go
              if not $env:PATH | str contains $GOPATH/bin {
                set -x PATH $env:PATH $GOPATH/bin
              end
            end
