---
tasks:
  - name: Install smartmontools
    winget:
      package: smartmontools.smartmontools
      state: ${{ package.state }}

  # get install path of ${env:ProgramFiles}\smartmontools\bin
  - name: smartctl path fact
    id: smartctl_path
    shell:
      command: Get-Command smartctlx | Select-Object -ExpandProperty Source

  - name: Install smartctl exporter
    xget:
      package: smartmontools/smartctl_exporter
      state: ${{ package.state }}
      args:
        - --to=${{ facts.local_bin_path | default("~/.local/bin") | join("smartctl_exporter") | extension("exe") }}
        - --upgrade-only
        - --asset=".zip"

  - name: Create Logon Task
    scheduled_task:
      state: ${{ package.state }}
      name: smartctl_exporter
      description: "Run smartctl_exporter on logon"
      actions:
        - execute: ${{ facts.local_bin_path | default("~/.local/bin") | join("smartctl_exporter") | extension("exe") }}
          arguments: "--smartctl.path={{ smartctl_path.stdout }} --web.listen-address=:9633"
      triggers:
        - type: "logon"
        - type: "startup"
      principal:
        user_id: S-1-5-20 # NETWORK SERVICE
        run_level: Highest
      settings:
        multiple_instances: IgnoreNew
        start_when_available: true
        run_only_if_network_available: true
      
