---

tasks:
  - name: "Create WSL Shim: ${{ inputs.command }}"
    when: 
      - inputs.command is defined 
      - facts.wsl_installed | default(false)
      - facts.os_family == 'windows'
    actions:
      - name: Create WSL Shim -> ${{ inputs.command }}
        template:
          # create: true
          # marker: ':: {mark} IRONSTATE MANAGED - {name}'
          # marker_name: "${{ 'Create WSL Shim -> ${{ inputs.command }}' | sha1 }}"
          dest: "${{ facts.local_bin_path | default('~/.local/bin') | join(inputs.command) }}.cmd"
          src: templates/shim.cmd.j2
          engine: jinja
          state: ${{ inputs.state | default(package.state) }}
          vars:
            command: "${{ inputs.command }}"
            args: "${{ inputs.args | default('') }}"
