---

tasks:

  - name: Install ${{ item }} (${{ facts.os_family }})
    apt:
      package: ${{ item }}
      state: ${{ package.state }}
    become: true
    when:
      - facts.is_debian
      - facts.os_family is not 'debian' # covered by the debian file auto inclusion
    items:
      - nodejs
      - npm
    