---

tasks:

  - name: Install Delta
    tags:
      - git
      - development
      - development.git
    xget:
      package: dandavison/delta
      state: ${{ git | enabled() | ternary("present", "absent") }}
      args:
        - --to=${{ facts.local_bin_path | join("delta") | extension("exe") }}
        - --ignore=.sbom.json
        - --ignore=musl
        - --asset=.tar.gz
        - --upgrade-only
    when:
      - git | enabled()
      - facts.os_family != 'alpine'

  - name: Install Delta
    tags:
      - git
      - development
      - development.git
    xget:
      package: dandavison/delta
      state: ${{ git | enabled() | ternary("present", "absent") }}
      args:
        - --to=${{ facts.local_bin_path | join("delta") | extension("exe") }}
        - --ignore=.sbom.json
        - --asset=.tar.gz
        - --upgrade-only
    when:
      - git | enabled()
      - facts.os_family == 'alpine'
