---

tasks:

  # git settings are under vars.git
  

  - name: Render global gitconfig
    tags: 
      - git
      - development
      - development.git
    blockinfile:
      state: ${{ git | enabled() | ternary("present", "absent") }}
      create: true
      template:
        src: templates/gitconfig.j2
        engine: jinja
      dest: ~/.gitconfig
      insertbefore: BOF

  - name: Render per-profile gitconfig
    tags: 
      - git
      - development
      - development.git
    items: ${{ vars.git.profiles | default([]) }}
    template:
      state: ${{ git | enabled() | ternary("present", "absent") }}
      # TODO: Consider using blockinfile instead of template for per-profile gitconfig
      # also consider allowing create / force for per-profile gitconfig
      # create: true
      # force: true
      src: templates/gitconfig.profile.j2
      dest: ~/.gitconfig-${{ item.name }}
      engine: jinja
      vars:
        profile: ${{ item }}

  - name: Render enterprise gitconfig
    tags: 
      - git
      - development
      - development.git
    when: github.enterprise is defined
    blockinfile:
      state: ${{ git | enabled() | ternary("present", "absent") }}
      template:
        src: templates/gitconfig.enterprise.urls.j2
        engine: jinja
        vars:
          enterprise: ${{ github.enterprise | default([]) }}
      dest: ~/.gitconfig