---

tasks:

  - name: Install Git
    tags:
      - development
      - development.git
    winget:
      package: Git.Git
      state: present

  - name: Install Delta
    tags:
      - development
      - development.git
    xget:
      package: dandavison/delta
      state: present
      args:
        - --to=${{ facts.local_bin_path | join("delta") | extension("exe") }}
        - --upgrade-only

  - name: Render global gitconfig
    tags: 
      - development
      - development.git
    blockinfile:
      create: true
      template:
        src: templates/gitconfig.j2
        engine: jinja
      dest: ~/.gitconfig
      insertbefore: BOF

  - name: Render per-profile gitconfig
    tags: 
      - development
      - development.git
    items: ${{ vars.git.profiles | default([]) }}
    template:
      # TODO: Consider using blockinfile instead of template for per-profile gitconfig
      # also consider allowing create / force for per-profile gitconfig
      # create: true
      # force: true
      src: templates/gitconfig.profile.j2
      dest: ~/.gitconfig-${{ item.name }}
      engine: jinja
      vars:
        profile: ${{ item }}

  - name: Render enterprise gitconfig
    tags: 
      - development
      - development.git
    when: github.enterprise is defined
    blockinfile:
      template:
        src: templates/gitconfig.enterprise.urls.j2
        engine: jinja
        vars:
          enterprise: ${{ github.enterprise | default([]) }}
      dest: ~/.gitconfig